#!/usr/bin/env bash

trap "exit" SIGINT

SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10        TREE_TYPE=random    LABEL_TYPE=random     TEST_START_INDEX=0    TEST_COUNT=5    LABEL_PERCENT='0.5' python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100       TREE_TYPE=random    LABEL_TYPE=random     TEST_START_INDEX=5    TEST_COUNT=5    LABEL_PERCENT='0.5' python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=1000      TREE_TYPE=random    LABEL_TYPE=random     TEST_START_INDEX=10   TEST_COUNT=5    LABEL_PERCENT='0.5' python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10000     TREE_TYPE=random    LABEL_TYPE=random     TEST_START_INDEX=15   TEST_COUNT=5    LABEL_PERCENT='0.5' python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=random    LABEL_TYPE=random     TEST_START_INDEX=20   TEST_COUNT=5    LABEL_PERCENT='0.5' python3 "${TEST_GENERATOR}"

SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10        TREE_TYPE=depth     LABEL_TYPE=random     TEST_START_INDEX=25   TEST_COUNT=5    DEPTH_COEFF='1'     python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100       TREE_TYPE=depth     LABEL_TYPE=random     TEST_START_INDEX=30   TEST_COUNT=5    DEPTH_COEFF='2'     python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=1000      TREE_TYPE=depth     LABEL_TYPE=random     TEST_START_INDEX=35   TEST_COUNT=5    DEPTH_COEFF='3'     python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10000     TREE_TYPE=depth     LABEL_TYPE=random     TEST_START_INDEX=40   TEST_COUNT=5    DEPTH_COEFF='3'     python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=depth     LABEL_TYPE=random     TEST_START_INDEX=45   TEST_COUNT=5    DEPTH_COEFF='4'     python3 "${TEST_GENERATOR}"

SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10        TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=50   TEST_COUNT=5    DEPTH_COEFF='4'     K_TYPE='random'  STRIPES_COUNT='10'    python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100       TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=55   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='random'  STRIPES_COUNT='100'   python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=1000      TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=60   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='random'  STRIPES_COUNT='100'   python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=10000     TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=65   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='random'  STRIPES_COUNT='50'    python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=70   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='random'  STRIPES_COUNT='50'    python3 "${TEST_GENERATOR}"

SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=75   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='big'     STRIPES_COUNT='50'    python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=80   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='average' STRIPES_COUNT='50'    python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=depth     LABEL_TYPE=stripes    TEST_START_INDEX=85   TEST_COUNT=5    DEPTH_COEFF='3'     K_TYPE='small'   STRIPES_COUNT='50'    python3 "${TEST_GENERATOR}"

SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=line      LABEL_TYPE=one_stripe TEST_START_INDEX=90   TEST_COUNT=5    K_TYPE='big'        python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=line      LABEL_TYPE=one_stripe TEST_START_INDEX=95   TEST_COUNT=5    K_TYPE='average'    python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=line      LABEL_TYPE=one_stripe TEST_START_INDEX=100  TEST_COUNT=5    K_TYPE='small'      python3 "${TEST_GENERATOR}"
SEED=${SEED} TEST_DIR="${TESTS_DIR}" VERTEX_COUNT=100000    TREE_TYPE=line      LABEL_TYPE=one_stripe TEST_START_INDEX=105  TEST_COUNT=5    K_TYPE='little'     python3 "${TEST_GENERATOR}"

for input_file in tests/input*.txt; do
    output_file=${input_file/input/output}
	"./${SOLUTION}" <"${input_file}" >"${output_file}"
    test_index=$([[ "${input_file}" =~ ([0-9]+) ]] && echo "${BASH_REMATCH[1]}")
    printf "[Test #%3s] generated output\n" "${test_index}"
done
